model_path:
  small: "./model/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  large: "./model/capybarahermes-2.5-mistral-7b.Q5_K_M.gguf"

model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: {'max_new_tokens': 512, 'temperature': 0.7, 'context_length': 4096, 'gpu_layers': 0}

chat_history_path: "./chat_sessions"
